"""first init

Revision ID: b880d32d1e78
Revises: 
Create Date: 2025-09-04 15:54:38.453573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b880d32d1e78'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('author', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('pic_url', sa.String(), nullable=True),
    sa.Column('difficulty', sa.Integer(), nullable=True),
    sa.CheckConstraint("author <> ''", name='ck_book_author_not_empty'),
    sa.CheckConstraint("title <> ''", name='ck_book_title_not_empty'),
    sa.CheckConstraint('difficulty BETWEEN 1 AND 6', name='ck_book_difficulty'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title', 'author', name='uq_book_title_author')
    )
    op.create_index('ix_book_difficulty', 'book', ['difficulty'], unique=False)
    op.create_index(op.f('ix_book_id'), 'book', ['id'], unique=False)
    op.create_table('chapter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('order_number', sa.Integer(), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('s3_url', sa.String(), nullable=False),
    sa.CheckConstraint("title <> ''", name='ck_chapter_title_not_empty'),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('book_id', 'order_number', name='uq_chapter_book_title')
    )
    op.create_index('ix_chapter_book_id', 'chapter', ['book_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_chapter_book_id', table_name='chapter')
    op.drop_table('chapter')
    op.drop_index(op.f('ix_book_id'), table_name='book')
    op.drop_index('ix_book_difficulty', table_name='book')
    op.drop_table('book')
    # ### end Alembic commands ###
