apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-data
  namespace: default
  labels:
    app: minio
    env: production
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi